#pour charger le fichier YML dans une variable
#@constants = YAML.load_file(Rails.root.join('config', 'constants.yml'))
#then @constants["texture_url"][1]
skills:
  Photography:
    url: 'photography_video'
    picto: 'fa fa-camera'
  Video:
    url: 'photography_video'
    picto: 'fa fa-camera'
  Graphic Design:
    url: 'graphic_design'
    picto: 'fa fa-pencil-square-o'
  Web Development:
    url: 'web_development'
    picto: 'fa fa-laptop'
  Web Marketing:
    url: 'marketing_studies'
    picto: 'fa fa-area-chart'

img_placeholder_url:
  0: 'v1505672486/texture13_fiifw9.jpg'
  1: 'v1505383045/texture/texture1_eh4j8f.jpg'
  2: 'v1505383045/texture/texture4_zqx2fb.jpg'
  3: 'v1505383045/texture/texture5_pzlmyr.jpg'
  4: 'v1505383046/texture/texture9_dohs8t.jpg'
  5: 'v1505383046/texture/texture10_xgxiwj.jpg'
  6: 'v1505383046/texture/texture11_zajsmd.jpg'

img_banner_url:
  packer: 'v1505688931/IApply_jfb8wq.jpg'
  crew: 'v1505688931/IAmACrew_jgqmuq.jpg'
  paris: 'v1505688931/IApply_jfb8wq.jpg'
